#!/usr/bin/env bash
# pilot.sh — one-command pilot deployment for a design-partner customer.
#
# Usage:
#   ./pilot.sh --client-id acme --anthropic-key sk-ant-... --openai-key sk-...
#   ./pilot.sh --client-id acme --anthropic-key ... --openai-key ... --base-port 8100
#
# What it does:
#   1. Validates args
#   2. Generates a random GATEWAY_MASTER_KEY for this client
#   3. Creates deploy/clients/<client-id>/ with .env + their own docker-compose.yml
#   4. Brings up the gateway + redis stack on the requested ports
#   5. Health-checks the gateway (10 attempts, 3s apart)
#   6. Runs a single-call smoke test
#   7. Prints a clean banner with the gateway URL, API key, sample curl
#
# Exits non-zero on any failure with a clear error.

set -euo pipefail

# --- Color helpers (skip if not a tty) -------------------------------------
if [ -t 1 ]; then
  C_RED=$(printf '\033[31m'); C_GRN=$(printf '\033[32m'); C_YEL=$(printf '\033[33m')
  C_BLU=$(printf '\033[34m'); C_BLD=$(printf '\033[1m'); C_RST=$(printf '\033[0m')
else
  C_RED=""; C_GRN=""; C_YEL=""; C_BLU=""; C_BLD=""; C_RST=""
fi
say()  { echo -e "${C_BLU}▸${C_RST} $*"; }
ok()   { echo -e "${C_GRN}✓${C_RST} $*"; }
warn() { echo -e "${C_YEL}!${C_RST} $*"; }
err()  { echo -e "${C_RED}✗${C_RST} $*" >&2; }

# --- Arg parsing -----------------------------------------------------------
CLIENT_ID=""
ANTHROPIC_KEY=""
OPENAI_KEY=""
BASE_PORT=8000
USAGE="Usage: $0 --client-id <name> --anthropic-key <key> --openai-key <key> [--base-port 8000]"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --client-id)     CLIENT_ID="$2";     shift 2 ;;
    --anthropic-key) ANTHROPIC_KEY="$2"; shift 2 ;;
    --openai-key)    OPENAI_KEY="$2";    shift 2 ;;
    --base-port)     BASE_PORT="$2";     shift 2 ;;
    -h|--help)       echo "$USAGE"; exit 0 ;;
    *)               err "unknown arg: $1"; echo "$USAGE" >&2; exit 1 ;;
  esac
done

if [[ -z "$CLIENT_ID" || -z "$ANTHROPIC_KEY" || -z "$OPENAI_KEY" ]]; then
  err "missing required arguments"; echo "$USAGE" >&2; exit 1
fi
if ! [[ "$CLIENT_ID" =~ ^[a-zA-Z0-9_-]+$ ]]; then
  err "client-id must be alphanumeric (dashes/underscores ok): got '$CLIENT_ID'"; exit 1
fi
if ! command -v docker >/dev/null 2>&1; then
  err "docker not found. Install Docker first: https://docs.docker.com/get-docker/"; exit 1
fi
if ! docker info >/dev/null 2>&1; then
  err "docker daemon not running or no permission. Try: sudo systemctl start docker"; exit 1
fi

# --- Paths -----------------------------------------------------------------
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_ROOT="$( cd "$SCRIPT_DIR/.." && pwd )"
CLIENT_DIR="$SCRIPT_DIR/clients/$CLIENT_ID"
GATEWAY_PORT=$BASE_PORT
REDIS_PORT=$((BASE_PORT + 379))     # 8000 -> 8379, predictable
INSIGHT_PORT=$((BASE_PORT + 1))     # 8000 -> 8001

say "Setting up pilot for client: ${C_BLD}$CLIENT_ID${C_RST}"
say "  Gateway port:  $GATEWAY_PORT"
say "  Redis port:    $REDIS_PORT"

# --- Generate per-client key + write .env ----------------------------------
mkdir -p "$CLIENT_DIR/logs"

MASTER_KEY="pilot-$(openssl rand -hex 12)"
COMPOSE_PROJECT="viren-${CLIENT_ID}"

cat > "$CLIENT_DIR/.env" <<EOF
# Auto-generated by pilot.sh — do not edit directly.
# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
CLIENT_ID=$CLIENT_ID
COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT
GATEWAY_PORT=$GATEWAY_PORT
REDIS_PORT=$REDIS_PORT
INSIGHT_PORT=$INSIGHT_PORT
OPENAI_API_KEY=$OPENAI_KEY
ANTHROPIC_API_KEY=$ANTHROPIC_KEY
GATEWAY_MASTER_KEY=$MASTER_KEY
SEMANTIC_CACHE_THRESHOLD=0.95
SEMANTIC_CACHE_TTL_SECONDS=86400
ENABLE_SEMANTIC_CACHE=true
ENABLE_CLASSIFIER=true
SHADOW_LOG_PATH=/app/shadow_log.jsonl
EOF
chmod 600 "$CLIENT_DIR/.env"

# --- Per-client compose file (different ports + named volume) -------------
cat > "$CLIENT_DIR/docker-compose.yml" <<'EOF'
# Per-client compose — generated by pilot.sh
services:
  redis:
    image: redis/redis-stack:7.4.0-v0
    ports:
      - "${REDIS_PORT}:6379"
      - "${INSIGHT_PORT}:8001"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  gateway:
    build:
      context: ../../../gateway/router
    ports:
      - "${GATEWAY_PORT}:8000"
    env_file: .env
    environment:
      REDIS_URL: redis://redis:6379
      LITELLM_CONFIG: /app/litellm_config.yaml
    volumes:
      - ../../../gateway/litellm_config.yaml:/app/litellm_config.yaml:ro
      - ./logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis-data:
EOF

say "Bringing up the gateway stack..."
(cd "$CLIENT_DIR" && docker compose --env-file .env up --build -d) || {
  err "docker compose up failed"; exit 1
}

# --- Health check ----------------------------------------------------------
say "Waiting for /health to return 200..."
HEALTH_URL="http://localhost:$GATEWAY_PORT/health"
HEALTHY=0
for i in 1 2 3 4 5 6 7 8 9 10; do
  sleep 3
  if curl -sS -m 5 "$HEALTH_URL" >/dev/null 2>&1; then
    BODY=$(curl -sS -m 5 "$HEALTH_URL")
    if echo "$BODY" | grep -q '"ok": *true'; then
      ok "gateway is healthy (attempt $i)"
      HEALTHY=1
      break
    fi
  fi
  say "  attempt $i/10 — gateway not ready yet"
done
if [ $HEALTHY -ne 1 ]; then
  err "gateway never came up healthy. Logs:"
  (cd "$CLIENT_DIR" && docker compose --env-file .env logs --tail=50 gateway) >&2
  err "Aborting."
  exit 1
fi

# --- One-call smoke test ---------------------------------------------------
say "Running a single smoke call..."
SMOKE_RESP=$(curl -sS -m 30 \
  -H "Authorization: Bearer $MASTER_KEY" \
  -H "Content-Type: application/json" \
  -d '{"model":"auto","messages":[{"role":"user","content":"Reply with the single word OK."}],"max_tokens":10}' \
  "http://localhost:$GATEWAY_PORT/v1/chat/completions" || true)

if echo "$SMOKE_RESP" | grep -qE '"content": *"OK"|"content": *"Ok"|"content": *"ok"'; then
  ok "smoke call returned a clean OK response"
else
  warn "smoke call did not return a clean OK. Raw response:"
  echo "$SMOKE_RESP" | head -c 1000
  echo
  warn "(gateway is up; this may be a model quirk — verify keys are valid)"
fi

# --- Banner ----------------------------------------------------------------
echo
echo -e "${C_GRN}${C_BLD}╔════════════════════════════════════════════════════════════════╗${C_RST}"
echo -e "${C_GRN}${C_BLD}║              VIREN — Pilot deployment READY                    ║${C_RST}"
echo -e "${C_GRN}${C_BLD}╚════════════════════════════════════════════════════════════════╝${C_RST}"
echo
echo -e "${C_BLD}Client:${C_RST}        $CLIENT_ID"
echo -e "${C_BLD}Gateway URL:${C_RST}   http://localhost:$GATEWAY_PORT/v1"
echo -e "${C_BLD}API key:${C_RST}       $MASTER_KEY"
echo -e "${C_BLD}Logs:${C_RST}          $CLIENT_DIR/logs/"
echo -e "${C_BLD}Stack:${C_RST}         $CLIENT_DIR/docker-compose.yml"
echo
echo -e "${C_BLD}Sample call:${C_RST}"
cat <<EOF
  curl -X POST http://localhost:$GATEWAY_PORT/v1/chat/completions \\
    -H "Authorization: Bearer $MASTER_KEY" \\
    -H "Content-Type: application/json" \\
    -d '{"model":"auto","messages":[{"role":"user","content":"Hello"}]}'
EOF
echo
echo -e "${C_BLD}Daily summary report:${C_RST}"
echo "  ./deploy/daily_summary.sh --client-id $CLIENT_ID"
echo
echo -e "${C_BLD}Teardown when pilot ends:${C_RST}"
echo "  ./deploy/teardown.sh --client-id $CLIENT_ID"
echo
ok "All set. Hand the URL + API key to the client's engineer."
